name: Build JOSS paper
on:
  push:
    paths: ["paper/**"]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: openjournals/openjournals-draft-action@v1
        with:
          journal: joss
          paper-path: paper/paper.md
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: joss-paper
          path: paper/paper.pdf
