name: Build JOSS paper

on:
  push:
    paths:
      - 'paper/**'
      - '.github/workflows/paper.yml'
  workflow_dispatch:

jobs:
  draft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@v1.0
        with:
          journal: joss
          paper-path: paper/paper.md

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: joss-paper
          path: paper/paper.pdf
